export const daftarBuah = [
  "Soekarno",
  "Mohammad Hatta",
  "Cut Nyak Dien",
  "Ki Hajar Dewantara",
  "R.A. Kartini",
  "Pangeran Diponegoro",
  "Gatot Soebroto",
  "Tuanku Imam Bonjol",
  "Sultan Agung",
  "Ki Ageng Gribig",
  "Teuku Umar",
  "Ki Ageng Selo",
  "Ki Ageng Pemanahan",
  "Jenderal Sudirman",
  "Tjut Meutia",
  "Bung Tomo",
  "Sultan Hasanuddin",
  "Kapitan Pattimura",
  "Ki Hadjar Dewantara",
  "Fatmawati Soekarno",
];
