export const daftarBuah = [
  "Crazy Cabe Cabean",
  "Makhluk Abadi Aneh",
  "Serbuk Tepung Terbang",
  "Teh Botol Mabok",
  "Es Krim Nyeleneh",
  "Tahu Bulat Binal",
  "Kolak Kolot Keliling",
  "Roti Sobek Sahur",
  "Gudeg Gila-Gilaan",
  "Selai Cinta Terlarang",
  "Sarden Mabuk Maut",
  "Permen Karet Kaget",
  "Telur Dadar Dengki",
  "Kerupuk Loyo Lucu",
  "Jus Alpukat Ambyar",
  "Kepiting Ngebut Nakal",
  "Kentang Garing Gokil",
  "Pempek Pede Penganten",
  "Cilok Cinta-Cintaaan",
  "Sosis Sapi Silet",
];
